services:

  db:
    hostname: db
    image: pgvector/pgvector:0.6.2-pg16
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
